/**
 *   TokenKind is a simple enumeration of the different kinds of tokens
 *   
 */
package miniJava.SyntacticAnalyzer;

public enum TokenKind {
    AND, ASSIGN, BOOLEAN, CLASS, COMMA, DIVIDE, ELSE, EOT, EQUALS, ERROR, FALSE, GREATEREQUAL, GREATERTHAN, ID, IF, INT,
    LBRACE, LBRACKET, LESSEQUAL, LESSTHAN, LPAREN, MINUS, NEW, NOT, NOTEQUAL, NULL, NUM, OR, PERIOD, PLUS, PRIVATE,
    PUBLIC, RBRACE, RBRACKET, RETURN, RPAREN, SEMICOLON, STATIC, THIS, TIMES, TRUE, VOID, WHILE
}